name: "Update the Table of Contents"

on: [push]

env:
  FILE: IPA-End-to-End.md

jobs:
  setup:
    name: "Update TOC"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Update Table of Contents"
      run: |
        t=$(mktemp)
        python3 toc.py "$FILE" > "$t"
        if diff -q "$FILE" "$t" 2>/dev/null; then
          mv "$t" "$FILE"
          git -c user.name="ToC Bot" -c user.email="toc@example.com" commit -m "Update ToC" "$FILE"
        fi

    - name: "Push Changes"
      if: ${{ github.ref_type == 'branch' }}
      run: |
        git push origin "${{ github.ref }}"
